module DogData
  BREEDS = 
    [
      { weight: { imperial: '6 - 13', metric: '3 - 6' },
        height: { imperial: '9 - 11.5', metric: '23 - 29' },
        name: 'Affenpinscher',
        bred_for: 'Small rodent hunting, lapdog',
        breed_group: 'Toy',
        life_span: '10 - 12 years',
        temperament: 'Stubborn, Curious, Playful, Adventurous, Active, Fun-loving',
        origin: 'Germany, France',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Affenpinscher.jpg/440px-Affenpinscher.jpg"
      },
      { weight: { imperial: '50 - 60', metric: '23 - 27' },
        height: { imperial: '25 - 27', metric: '64 - 69' },
        name: 'Afghan Hound',
        country_code: 'AG',
        bred_for: 'Coursing and hunting',
        breed_group: 'Hound',
        life_span: '10 - 13 years',
        temperament: 'Aloof, Clownish, Dignified, Independent, Happy',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/6/69/Afghane.jpg"
      },
      { weight: { imperial: '40 - 65', metric: '18 - 29' },
        height: { imperial: '21 - 23', metric: '53 - 58' },
        name: 'Airedale Terrier',
        bred_for: 'Badger, otter hunting',
        breed_group: 'Terrier',
        life_span: '10 - 13 years',
        temperament: 'Outgoing, Friendly, Alert, Confident, Intelligent, Courageous',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Airedale-terrier-charles14m.jpg/440px-Airedale-terrier-charles14m.jpg"
      },
      { weight: { imperial: '90 - 120', metric: '41 - 54' },
        height: { imperial: '28 - 34', metric: '71 - 86' },
        name: 'Akbash Dog',
        bred_for: 'Sheep guarding',
        breed_group: 'Working',
        life_span: '10 - 12 years',
        temperament: 'Loyal, Independent, Intelligent, Brave',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Akbash_Dog_male_2016.jpg/440px-Akbash_Dog_male_2016.jpg"
      },
      { weight: { imperial: '65 - 115', metric: '29 - 52' },
        height: { imperial: '24 - 28', metric: '61 - 71' },
        name: 'Akita',
        bred_for: 'Hunting bears',
        breed_group: 'Working',
        life_span: '10 - 14 years',
        temperament: 'Docile, Alert, Responsive, Dignified, Composed, Friendly, Receptive, Faithful, Courageous',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/American-akita.jpg/300px-American-akita.jpg"
      },
      { weight: { imperial: '55 - 90', metric: '25 - 41' },
        height: { imperial: '18 - 24', metric: '46 - 61' },
        name: 'Alapaha Blue Blood Bulldog',
        description: 'The Alapaha Blue Blood Bulldog is a well-developed, exaggerated bulldog with a broad head and natural drop ears. The prominent muzzle is covered by loose upper lips. The prominent eyes are set well apart. The Alapaha\'s coat is relatively short and fairly stiff. Preferred colors are blue merle, brown merle, or red merle all trimmed in white or chocolate and white. Also preferred are the glass eyes (blue) or marble eyes (brown and blue mixed in a single eye). The ears and tail are never trimmed or docked. The body is sturdy and very muscular. The well-muscled hips are narrower than the chest. The straight back is as long as the dog is high at the shoulders. The dewclaws are never removed and the feet are cat-like.',
        bred_for: 'Guarding',
        breed_group: 'Mixed',
        life_span: '12 - 13 years',
        history: '',
        temperament: 'Loving, Protective, Trainable, Dutiful, Responsible',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Alapaha_Blue-Blood_Bulldog.jpg/440px-Alapaha_Blue-Blood_Bulldog.jpg"
      },
      { weight: { imperial: '38 - 50', metric: '17 - 23' },
        height: { imperial: '23 - 26', metric: '58 - 66' },
        name: 'Alaskan Husky',
        bred_for: 'Sled pulling',
        breed_group: 'Mixed',
        life_span: '10 - 13 years',
        temperament: 'Friendly, Energetic, Loyal, Gentle, Confident',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Black-Magic-Big-Boy.jpg/440px-Black-Magic-Big-Boy.jpg"
      },
      { weight: { imperial: '65 - 100', metric: '29 - 45' },
        height: { imperial: '23 - 25', metric: '58 - 64' },
        name: 'Alaskan Malamute',
        bred_for: 'Hauling heavy freight, Sled pulling',
        breed_group: 'Working',
        life_span: '12 - 15 years',
        temperament: 'Friendly, Affectionate, Devoted, Loyal, Dignified, Playful',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Alaskan_Malamute_6.jpg/440px-Alaskan_Malamute_6.jpg"
      },
      { weight: { imperial: '60 - 120', metric: '27 - 54' },
        height: { imperial: '22 - 27', metric: '56 - 69' },
        name: 'American Bulldog',
        breed_group: 'Working',
        life_span: '10 - 12 years',
        temperament: 'Friendly, Assertive, Energetic, Loyal, Gentle, Confident, Dominant',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/BUCKEYE_2010_ANCHOR_BULLY_RASCALZ.jpg/440px-BUCKEYE_2010_ANCHOR_BULLY_RASCALZ.jpg"
      },
      { weight: { imperial: '20 - 40', metric: '9 - 18' },
        height: { imperial: '15 - 19', metric: '38 - 48' },
        name: 'American Eskimo Dog',
        country_code: 'US',
        bred_for: 'Circus performer',
        breed_group: 'Non-Sporting',
        life_span: '12 - 15 years',
        temperament: 'Friendly, Alert, Reserved, Intelligent, Protective',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/American_Eskimo_Dog_portrait.jpg/500px-American_Eskimo_Dog_portrait.jpg"
      },
      { weight: { imperial: '65 - 75', metric: '29 - 34' },
        height: { imperial: '21 - 28', metric: '53 - 71' },
        name: 'American Foxhound',
        country_code: 'US',
        bred_for: 'Fox hunting, scent hound',
        breed_group: 'Hound',
        life_span: '8 - 15 years',
        temperament: 'Kind, Sweet-Tempered, Loyal, Independent, Intelligent, Loving',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/e/e7/AmericanFoxhound2.jpg"
      },
      { weight: { imperial: '30 - 60', metric: '14 - 27' },
        height: { imperial: '17 - 21', metric: '43 - 53' },
        name: 'American Pit Bull Terrier',
        country_code: 'US',
        bred_for: 'Fighting',
        breed_group: 'Terrier',
        life_span: '10 - 15 years',
        temperament: 'Strong Willed, Stubborn, Friendly, Clownish, Affectionate, Loyal, Obedient, Intelligent, Courageous',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Ginger_December_3579836414e4b5ce786eoPitBull.jpg/440px-Ginger_December_3579836414e4b5ce786eoPitBull.jpg"
      },
      { weight: { imperial: '50 - 60', metric: '23 - 27' },
        height: { imperial: '17 - 19', metric: '43 - 48' },
        name: 'American Staffordshire Terrier',
        country_code: 'US',
        bred_for: '',
        breed_group: 'Terrier',
        life_span: '12 - 15 years',
        temperament: 'Tenacious, Friendly, Devoted, Loyal, Attentive, Courageous',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/AMERICAN_STAFFORDSHIRE_TERRIER%2C_Zican%E2%80%99s_Bz_Ez_Dragon_%2824208348891%29.2.jpg/440px-AMERICAN_STAFFORDSHIRE_TERRIER%2C_Zican%E2%80%99s_Bz_Ez_Dragon_%2824208348891%29.2.jpg"
      },
      { weight: { imperial: '25 - 45', metric: '11 - 20' },
        height: { imperial: '15 - 18', metric: '38 - 46' },
        name: 'American Water Spaniel',
        country_code: 'US',
        bred_for: 'Bird flushing and retrieving',
        breed_group: 'Sporting',
        life_span: '10 - 12 years',
        temperament: 'Friendly, Energetic, Obedient, Intelligent, Protective, Trainable',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Chien_d%27eau_americain_champion_1.JPG/440px-Chien_d%27eau_americain_champion_1.JPG"
      },
      { weight: { imperial: '80 - 150', metric: '36 - 68' },
        height: { imperial: '27 - 29', metric: '69 - 74' },
        name: 'Anatolian Shepherd Dog',
        bred_for: 'Livestock herding',
        breed_group: 'Working',
        life_span: '11 - 13 years',
        temperament: 'Steady, Bold, Independent, Confident, Intelligent, Proud',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Varish.jpg/440px-Varish.jpg"
      },
      { weight: { imperial: '48 - 55', metric: '22 - 25' },
        height: { imperial: '20 - 22', metric: '51 - 56' },
        name: 'Appenzeller Sennenhund',
        bred_for: 'Herding livestock, pulling carts, and guarding the farm',
        life_span: '12 – 14 years',
        temperament: 'Reliable, Fearless, Energetic, Lively, Self-assured',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/9/9e/Dara_essy.jpg"
      },
      { weight: { imperial: '44 - 62', metric: '20 - 28' },
        height: { imperial: '17 - 20', metric: '43 - 51' },
        name: 'Australian Cattle Dog',
        country_code: 'AU',
        bred_for: 'Cattle herding, herding trials',
        breed_group: 'Herding',
        life_span: '12 - 14 years',
        temperament: 'Cautious, Energetic, Loyal, Obedient, Protective, Brave',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/ACD-blue-spud.jpg/440px-ACD-blue-spud.jpg"
      },
      { weight: { imperial: '31 - 46', metric: '14 - 21' },
        height: { imperial: '17 - 20', metric: '43 - 51' },
        name: 'Australian Kelpie',
        country_code: 'AU',
        bred_for: 'Farm dog, Cattle herding',
        breed_group: 'Herding',
        life_span: '10 - 13 years',
        temperament: 'Friendly, Energetic, Alert, Loyal, Intelligent, Eager',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Hilu_the_Australian_Kelpie_dog.jpg/440px-Hilu_the_Australian_Kelpie_dog.jpg"
      },
      { weight: { imperial: '35 - 65', metric: '16 - 29' },
        height: { imperial: '18 - 23', metric: '46 - 58' },
        name: 'Australian Shepherd',
        country_code: 'AU',
        bred_for: 'Sheep herding',
        breed_group: 'Herding',
        life_span: '12 - 16 years',
        temperament: 'Good-natured, Affectionate, Intelligent, Active, Protective',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Redtriaussie01.jpg/440px-Redtriaussie01.jpg"
      },
      { weight: { imperial: '14 - 16', metric: '6 - 7' },
        height: { imperial: '10 - 11', metric: '25 - 28' },
        name: 'Australian Terrier',
        country_code: 'AU',
        bred_for: 'Cattle herdering, hunting snakes and rodents',
        breed_group: 'Terrier',
        life_span: '15 years',
        temperament: 'Spirited, Alert, Loyal, Companionable, Even Tempered, Courageous',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Australian_Terrier_-_Puppy.jpg/440px-Australian_Terrier_-_Puppy.jpg"
      },
      { weight: { imperial: '33 - 55', metric: '15 - 25' },
        height: { imperial: '23 - 29', metric: '58 - 74' },
        name: 'Azawakh',
        bred_for: 'Livestock guardian, hunting',
        breed_group: 'Hound',
        life_span: '10 - 13 years',
        temperament: 'Aloof, Affectionate, Attentive, Rugged, Fierce, Refined',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Chart_afryka%C5%84ski_Azawakh_II_654.jpg/440px-Chart_afryka%C5%84ski_Azawakh_II_654.jpg"
      },
      { weight: { imperial: '40 - 65', metric: '18 - 29' },
        height: { imperial: '20 - 26', metric: '51 - 66' },
        name: 'Barbet',
        bred_for: 'Hunting water game',
        life_span: '13 – 15 years',
        temperament: 'Obedient, Companionable, Intelligent, Joyful',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Ottavia.jpg/300px-Ottavia.jpg"
      },
      { weight: { imperial: '22 - 24', metric: '10 - 11' },
        height: { imperial: '16 - 17', metric: '41 - 43' },
        name: 'Basenji',
        bred_for: 'Hunting',
        breed_group: 'Hound',
        life_span: '10 - 12 years',
        temperament: 'Affectionate, Energetic, Alert, Curious, Playful, Intelligent',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Basenji_Profile_%28loosercrop%29.jpg/440px-Basenji_Profile_%28loosercrop%29.jpg"
      },
      { weight: { imperial: '35 - 40', metric: '16 - 18' },
        height: { imperial: '13 - 15', metric: '33 - 38' },
        name: 'Basset Bleu de Gascogne',
        bred_for: 'Hunting on foot.',
        breed_group: 'Hound',
        life_span: '10 - 14 years',
        temperament: 'Affectionate, Lively, Agile, Curious, Happy, Active',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Basset_bleu_de_Gascogne.jpg/440px-Basset_bleu_de_Gascogne.jpg"
      },
      { weight: { imperial: '50 - 65', metric: '23 - 29' },
        height: { imperial: '14', metric: '36' },
        name: 'Basset Hound',
        bred_for: 'Hunting by scent',
        breed_group: 'Hound',
        life_span: '12 - 15 years',
        temperament: 'Tenacious, Friendly, Affectionate, Devoted, Sweet-Tempered, Gentle',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/8/87/Bvdb-bassethound1.jpg"
      },
      { weight: { imperial: '20 - 35', metric: '9 - 16' },
        height: { imperial: '13 - 15', metric: '33 - 38' },
        name: 'Beagle',
        bred_for: 'Rabbit, hare hunting',
        breed_group: 'Hound',
        life_span: '13 - 16 years',
        temperament: 'Amiable, Even Tempered, Excitable, Determined, Gentle, Intelligent',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Bronco_the_Beagle.JPG/440px-Bronco_the_Beagle.JPG"
      },
      { weight: { imperial: '45 - 55', metric: '20 - 25' },
        height: { imperial: '20 - 22', metric: '51 - 56' },
        name: 'Bearded Collie',
        bred_for: 'Sheep herding',
        breed_group: 'Herding',
        life_span: '12 - 14 years',
        temperament: 'Self-confidence, Hardy, Lively, Alert, Intelligent, Active',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Bearded_collie_and_a_rope.jpg/440px-Bearded_collie_and_a_rope.jpg"
      },
      { weight: { imperial: '80 - 110', metric: '36 - 50' },
        height: { imperial: '24 - 27.5', metric: '61 - 70' },
        name: 'Beauceron',
        bred_for: 'Boar herding, hunting, guarding',
        breed_group: 'Herding',
        life_span: '10 - 12 years',
        temperament: 'Fearless, Friendly, Intelligent, Protective, Calm',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Owczarek_francuski_beauceron_009pl.jpg/440px-Owczarek_francuski_beauceron_009pl.jpg"
      },
      { weight: { imperial: '17 - 23', metric: '8 - 10' },
        height: { imperial: '15 - 16', metric: '38 - 41' },
        name: 'Bedlington Terrier',
        bred_for: 'Killing rat, badger, other vermin',
        breed_group: 'Terrier',
        life_span: '14 - 16 years',
        temperament: 'Affectionate, Spirited, Intelligent, Good-tempered',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Boutchie_apres_championnat_004.JPG/440px-Boutchie_apres_championnat_004.JPG"
      },
      { weight: { imperial: '40 - 80', metric: '18 - 36' },
        height: { imperial: '22 - 26', metric: '56 - 66' },
        name: 'Belgian Malinois',
        bred_for: 'Stock herding',
        breed_group: 'Herding',
        life_span: '12 - 14 years',
        temperament: 'Watchful, Alert, Stubborn, Friendly, Confident, Hard-working, Active, Protective',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Female_Malinois_2005-01-29.jpg/440px-Female_Malinois_2005-01-29.jpg"
      },
      { weight: { imperial: '40 - 65', metric: '18 - 29' },
        height: { imperial: '22 - 26', metric: '56 - 66' },
        name: 'Belgian Tervuren',
        bred_for: 'Guarding, Drafting, Police work.',
        breed_group: 'Herding',
        life_span: '10 - 12 years',
        temperament: 'Energetic, Alert, Loyal, Intelligent, Attentive, Protective',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Himbis_Happy_Hana.jpg/440px-Himbis_Happy_Hana.jpg"
      },
      { weight: { imperial: '65 - 120', metric: '29 - 54' },
        height: { imperial: '23 - 27.5', metric: '58 - 70' },
        name: 'Bernese Mountain Dog',
        bred_for: 'Draft work',
        breed_group: 'Working',
        life_span: '7 - 10 years',
        temperament: 'Affectionate, Loyal, Intelligent, Faithful',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Bernese_Mountain_Dog_-_9_months.JPG/340px-Bernese_Mountain_Dog_-_9_months.JPG"
      },
      { weight: { imperial: '10 - 18', metric: '5 - 8' },
        height: { imperial: '9.5 - 11.5', metric: '24 - 29' },
        name: 'Bichon Frise',
        bred_for: 'Companion',
        breed_group: 'Non-Sporting',
        life_span: '15 years',
        temperament: 'Feisty, Affectionate, Cheerful, Playful, Gentle, Sensitive',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Bichon_Fris%C3%A9_-_studdogbichon.jpg/440px-Bichon_Fris%C3%A9_-_studdogbichon.jpg"
      },
      { weight: { imperial: '65 - 100', metric: '29 - 45' },
        height: { imperial: '23 - 27', metric: '58 - 69' },
        name: 'Black and Tan Coonhound',
        bred_for: 'Hunting raccoons, night hunting',
        breed_group: 'Hound',
        life_span: '10 - 12 years',
        temperament: 'Easygoing, Gentle, Adaptable, Trusting, Even Tempered, Lovable',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Black_%26_Tan_Coonhound_2.JPG/440px-Black_%26_Tan_Coonhound_2.JPG"
      },
      { weight: { imperial: '80 - 110', metric: '36 - 50' },
        height: { imperial: '23 - 27', metric: '58 - 69' },
        name: 'Bloodhound',
        bred_for: 'Trailing',
        breed_group: 'Hound',
        life_span: '8 - 10 years',
        temperament: 'Stubborn, Affectionate, Gentle, Even Tempered',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Bloodhound_2.jpg/440px-Bloodhound_2.jpg"
      },
      { weight: { imperial: '45 - 80', metric: '20 - 36' },
        height: { imperial: '21 - 27', metric: '53 - 69' },
        name: 'Bluetick Coonhound',
        bred_for: 'Hunting with a superior sense of smell.',
        breed_group: 'Hound',
        life_span: '12 - 14 years',
        temperament: 'Friendly, Intelligent, Active',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/BluetickCoonhound.jpg/440px-BluetickCoonhound.jpg"
      },
      { weight: { imperial: '110 - 200', metric: '50 - 91' },
        height: { imperial: '22 - 27', metric: '56 - 69' },
        name: 'Boerboel',
        bred_for: 'Guarding the homestead, farm work.',
        breed_group: 'Working',
        life_span: '10 - 12 years',
        temperament: 'Obedient, Confident, Intelligent, Dominant, Territorial',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Boerboel_wiki.jpg/440px-Boerboel_wiki.jpg"
      },
      { weight: { imperial: '30 - 45', metric: '14 - 20' },
        height: { imperial: '18 - 22', metric: '46 - 56' },
        name: 'Border Collie',
        bred_for: 'Sheep herder',
        breed_group: 'Herding',
        life_span: '12 - 16 years',
        temperament: 'Tenacious, Keen, Energetic, Responsive, Alert, Intelligent',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Border_Collie_blanca_y_negra_Cachorra_%28Bimba_de_los_Baganicos%29.jpg/440px-Border_Collie_blanca_y_negra_Cachorra_%28Bimba_de_los_Baganicos%29.jpg"
      },
      { weight: { imperial: '11.5 - 15.5', metric: '5 - 7' },
        height: { imperial: '11 - 16', metric: '28 - 41' },
        name: 'Border Terrier',
        bred_for: 'Fox bolting, ratting',
        breed_group: 'Terrier',
        life_span: '12 - 14 years',
        temperament: 'Fearless, Affectionate, Alert, Obedient, Intelligent, Even Tempered',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Border_Terrier.jpg/440px-Border_Terrier.jpg"
      },
      { weight: { imperial: '10 - 25', metric: '5 - 11' },
        height: { imperial: '16 - 17', metric: '41 - 43' },
        name: 'Boston Terrier',
        bred_for: 'Ratting, Companionship',
        breed_group: 'Non-Sporting',
        life_span: '11 - 13 years',
        temperament: 'Friendly, Lively, Intelligent',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Boston_Terrier_male.jpg/440px-Boston_Terrier_male.jpg"
      },
      { weight: { imperial: '70 - 110', metric: '32 - 50' },
        height: { imperial: '23.5 - 27.5', metric: '60 - 70' },
        name: 'Bouvier des Flandres',
        bred_for: 'Cattle herding',
        breed_group: 'Herding',
        life_span: '10 - 15 years',
        temperament: 'Protective, Loyal, Gentle, Intelligent, Familial, Rational',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Bouvier.JPG/440px-Bouvier.JPG"
      },
      { weight: { imperial: '50 - 70', metric: '23 - 32' },
        height: { imperial: '21.5 - 25', metric: '55 - 64' },
        name: 'Boxer',
        bred_for: 'Bull-baiting, guardian',
        breed_group: 'Working',
        life_span: '8 - 10 years',
        temperament: 'Devoted, Fearless, Friendly, Cheerful, Energetic, Loyal, Playful, Confident, Intelligent, Bright, Brave, Calm',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Boxer_dog.jpg/400px-Boxer_dog.jpg"
      },
      { weight: { imperial: '25 - 40', metric: '11 - 18' },
        height: { imperial: '14 - 18', metric: '36 - 46' },
        name: 'Boykin Spaniel',
        bred_for: 'Turkey retrieving',
        breed_group: 'Sporting',
        life_span: '10 - 14 years',
        temperament: 'Friendly, Energetic, Companionable, Intelligent, Eager, Trainable',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Boykin_Spaniel.jpg/440px-Boykin_Spaniel.jpg"
      },
      { weight: { imperial: '55 - 88', metric: '25 - 40' },
        height: { imperial: '21.5 - 26.5', metric: '55 - 67' },
        name: 'Bracco Italiano',
        bred_for: 'Versatile gun dog',
        breed_group: 'Sporting',
        life_span: '10 - 12 years',
        temperament: 'Stubborn, Affectionate, Loyal, Playful, Companionable, Trainable',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Giotto_BI.jpg/440px-Giotto_BI.jpg"
      },
      { weight: { imperial: '70 - 90', metric: '32 - 41' },
        height: { imperial: '22 - 27', metric: '56 - 69' },
        name: 'Briard',
        bred_for: 'Herding, guarding sheep',
        breed_group: 'Herding',
        life_span: '10 - 12 years',
        temperament: 'Fearless, Loyal, Obedient, Intelligent, Faithful, Protective',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Briard_fauve.JPG/440px-Briard_fauve.JPG"
      },
      { weight: { imperial: '30 - 45', metric: '14 - 20' },
        height: { imperial: '17.5 - 20.5', metric: '44 - 52' },
        name: 'Brittany',
        bred_for: 'Pointing, retrieving',
        breed_group: 'Sporting',
        life_span: '12 - 14 years',
        temperament: 'Agile, Adaptable, Quick, Intelligent, Attentive, Happy',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/American_Brittany_standing.jpg/440px-American_Brittany_standing.jpg"
      },
      { weight: { imperial: '50 - 70', metric: '23 - 32' },
        height: { imperial: '21 - 22', metric: '53 - 56' },
        name: 'Bull Terrier',
        bred_for: 'Bull baiting, Fighting',
        breed_group: 'Terrier',
        life_span: '10 - 12 years',
        temperament: 'Trainable, Protective, Sweet-Tempered, Keen, Active',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Close_up_of_a_Bull_Terrier.jpg/508px-Close_up_of_a_Bull_Terrier.jpg"
      },
      { weight: { imperial: '100 - 130', metric: '45 - 59' },
        height: { imperial: '24 - 27', metric: '61 - 69' },
        name: 'Bullmastiff',
        bred_for: 'Estate guardian',
        breed_group: 'Working',
        life_span: '8 - 12 years',
        temperament: 'Docile, Reliable, Devoted, Alert, Loyal, Reserved, Loving, Protective, Powerful, Calm, Courageous',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Bullmastiff_edited.JPG/440px-Bullmastiff_edited.JPG"
      },
      { weight: { imperial: '13 - 14', metric: '6 - 6' },
        height: { imperial: '9 - 10', metric: '23 - 25' },
        name: 'Cairn Terrier',
        bred_for: 'Bolting of otter, foxes, other vermin',
        breed_group: 'Terrier',
        life_span: '14 - 15 years',
        temperament: 'Hardy, Fearless, Assertive, Gay, Intelligent, Active',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Cairn_Terrier_-_002.jpg/440px-Cairn_Terrier_-_002.jpg"
      },
      { weight: { imperial: '88 - 120', metric: '40 - 54' },
        height: { imperial: '23.5 - 27.5', metric: '60 - 70' },
        name: 'Cane Corso',
        bred_for: 'Companion, guard dog, and hunter',
        breed_group: 'Working',
        life_span: '10 - 11 years',
        temperament: 'Trainable, Reserved, Stable, Quiet, Even Tempered, Calm',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/CaneCorso_%2823%29.jpg/440px-CaneCorso_%2823%29.jpg"
      },
      { weight: { imperial: '25 - 38', metric: '11 - 17' },
        height: { imperial: '10.5 - 12.5', metric: '27 - 32' },
        name: 'Cardigan Welsh Corgi',
        bred_for: 'Cattle droving',
        breed_group: 'Herding',
        life_span: '12 - 14 years',
        temperament: 'Affectionate, Devoted, Alert, Companionable, Intelligent, Active',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Cardigan_Welsh_Corgi%2C_Profile.png/440px-Cardigan_Welsh_Corgi%2C_Profile.png"
      },
      { weight: { imperial: '50 - 95', metric: '23 - 43' },
        height: { imperial: '20 - 26', metric: '51 - 66' },
        name: 'Catahoula Leopard Dog',
        bred_for: 'Driving livestock',
        breed_group: 'Herding',
        life_span: '10 - 12 years',
        temperament: 'Energetic, Inquisitive, Independent, Gentle, Intelligent, Loving',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/02._Coahoma_Arkansas_Logan.jpg/440px-02._Coahoma_Arkansas_Logan.jpg"
      },
      { weight: { imperial: '80 - 100', metric: '36 - 45' },
        height: { imperial: '24 - 33.5', metric: '61 - 85' },
        name: 'Caucasian Shepherd (Ovcharka)',
        bred_for: 'Guard dogs, defending sheep from predators, mainly wolves, jackals and bears',
        breed_group: 'Working',
        life_span: '10 - 12 years',
        temperament: 'Alert, Quick, Dominant, Powerful, Calm, Strong',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Owczarek_kaukaski_65.jpg/440px-Owczarek_kaukaski_65.jpg"
      },
      { weight: { imperial: '13 - 18', metric: '6 - 8' },
        height: { imperial: '12 - 13', metric: '30 - 33' },
        name: 'Cavalier King Charles Spaniel',
        bred_for: 'Flushing small birds, companion',
        breed_group: 'Toy',
        life_span: '10 - 14 years',
        temperament: 'Fearless, Affectionate, Sociable, Patient, Playful, Adaptable',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/CarterBIS.Tiki.13.6.09.jpg/440px-CarterBIS.Tiki.13.6.09.jpg"
      },
      { weight: { imperial: '55 - 80', metric: '25 - 36' },
        height: { imperial: '21 - 26', metric: '53 - 66' },
        name: 'Chesapeake Bay Retriever',
        bred_for: 'Water Retriever',
        breed_group: 'Sporting',
        life_span: '10 - 13 years',
        temperament: 'Affectionate, Intelligent, Quiet, Dominant, Happy, Protective',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/CH_Chesapeake.jpg/440px-CH_Chesapeake.jpg"
      },
      { weight: { imperial: '10 - 13', metric: '5 - 6' },
        height: { imperial: '11 - 13', metric: '28 - 33' },
        name: 'Chinese Crested',
        bred_for: 'Ratting, lapdog, curio',
        breed_group: 'Toy',
        life_span: '10 - 14 years',
        temperament: 'Affectionate, Sweet-Tempered, Lively, Alert, Playful, Happy',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/IndyStands.jpg/440px-IndyStands.jpg"
      },
      { weight: { imperial: '45 - 60', metric: '20 - 27' },
        height: { imperial: '18 - 20', metric: '46 - 51' },
        name: 'Chinese Shar-Pei',
        bred_for: 'Fighting',
        breed_group: 'Non-Sporting',
        life_span: '10 years',
        temperament: 'Suspicious, Affectionate, Devoted, Reserved, Independent, Loving',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Adult_sharpei.jpg"
      },
      { weight: { imperial: '50 - 90', metric: '23 - 41' },
        height: { imperial: '22 - 26', metric: '56 - 66' },
        name: 'Chinook',
        bred_for: 'Sled pulling',
        breed_group: 'Working',
        life_span: '12 - 15 years',
        temperament: 'Friendly, Alert, Dignified, Intelligent, Calm',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/8/84/Mountan_Laurel_Ajax_the_Chinook_dog.jpg"
      },
      { weight: { imperial: '40 - 70', metric: '18 - 32' },
        height: { imperial: '17 - 20', metric: '43 - 51' },
        name: 'Chow Chow',
        bred_for: 'Guardian, cart pulling, hunting',
        breed_group: 'Non-Sporting',
        life_span: '12 - 15 years',
        temperament: 'Aloof, Loyal, Independent, Quiet',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Chow-chow_in_Tallinn.JPG/440px-Chow-chow_in_Tallinn.JPG"
      },
      { weight: { imperial: '55 - 85', metric: '25 - 39' },
        height: { imperial: '17 - 20', metric: '43 - 51' },
        name: 'Clumber Spaniel',
        bred_for: 'Bird flushing, retrieving',
        breed_group: 'Sporting',
        life_span: '10 - 12 years',
        temperament: 'Affectionate, Loyal, Dignified, Gentle, Calm, Great-hearted',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Clumber_spaniel_rybnik_kamien_pppl.jpg/440px-Clumber_spaniel_rybnik_kamien_pppl.jpg"
      },
      { weight: { imperial: '20 - 30', metric: '9 - 14' },
        height: { imperial: '14 - 15', metric: '36 - 38' },
        name: 'Cocker Spaniel',
        bred_for: 'Bird flushing, retrieving',
        breed_group: 'Sporting',
        life_span: '12 - 15 years',
        temperament: 'Trainable, Friendly, Affectionate, Playful, Quiet, Faithful',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/EnglishCockerSpaniel_simon.jpg/440px-EnglishCockerSpaniel_simon.jpg"
      },
      { weight: { imperial: '20 - 30', metric: '9 - 14' },
        height: { imperial: '14 - 15', metric: '36 - 38' },
        name: 'Cocker Spaniel (American)',
        bred_for: 'Hunting the American woodcock',
        breed_group: 'Sporting',
        life_span: '12 - 15 years',
        temperament: 'Outgoing, Sociable, Trusting, Joyful, Even Tempered, Merry',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/American_Cocker_in_Tallinn_2.JPG/440px-American_Cocker_in_Tallinn_2.JPG"
      },
      { weight: { imperial: '9 - 15', metric: '4 - 7' },
        height: { imperial: '9 - 11', metric: '23 - 28' },
        name: 'Coton de Tulear',
        bred_for: 'Accompanying ladies on long sea voyages, ratters onboard ship.',
        breed_group: 'Non-Sporting',
        life_span: '13 - 16 years',
        temperament: 'Affectionate, Lively, Playful, Intelligent, Trainable, Vocal',
        image_url: "https://upload.wikimedia.org/wikipedia/en/thumb/7/7f/Coton_de_Tulear_smiling_on_the_lawn.jpeg/440px-Coton_de_Tulear_smiling_on_the_lawn.jpeg"
      },
      { weight: { imperial: '50 - 55', metric: '23 - 25' },
        height: { imperial: '19 - 23', metric: '48 - 58' },
        name: 'Dalmatian',
        bred_for: 'Carriage dog - trot alongside carriages to protect the occupants from banditry or other interference',
        breed_group: 'Non-Sporting',
        life_span: '10 - 13 years',
        temperament: 'Outgoing, Friendly, Energetic, Playful, Sensitive, Intelligent, Active',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Dalmatian_puppy.JPG/300px-Dalmatian_puppy.JPG"
      },
      { weight: { imperial: '66 - 88', metric: '30 - 40' },
        height: { imperial: '24 - 28', metric: '61 - 71' },
        name: 'Doberman Pinscher',
        bred_for: 'Guardian',
        breed_group: 'Working',
        life_span: '10 years',
        temperament: 'Fearless, Energetic, Alert, Loyal, Obedient, Confident, Intelligent',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/0Doberman-40172501920.jpg/440px-0Doberman-40172501920.jpg"
      },
      { weight: { imperial: '80 - 100', metric: '36 - 45' },
        height: { imperial: '23.5 - 27', metric: '60 - 69' },
        name: 'Dogo Argentino',
        bred_for: 'Big-game hunting',
        breed_group: 'Working',
        life_span: '10 - 12 years',
        temperament: 'Friendly, Affectionate, Cheerful, Loyal, Tolerant, Protective',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/0Dogo-argentino-22122251920.jpg/440px-0Dogo-argentino-22122251920.jpg"
      },
      { weight: { imperial: '50 - 70', metric: '23 - 32' },
        height: { imperial: '22 - 24.5', metric: '56 - 62' },
        name: 'Dutch Shepherd',
        bred_for: 'Farms, watchdog, guard duty',
        life_span: '15 years',
        temperament: 'Reliable, Affectionate, Alert, Loyal, Obedient, Trainable',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Long-haired_Dutch_Shepherd_4.JPG/440px-Long-haired_Dutch_Shepherd_4.JPG"
      },
      { weight: { imperial: '45 - 80', metric: '20 - 36' },
        height: { imperial: '24 - 25', metric: '61 - 64' },
        name: 'English Setter',
        bred_for: 'Bird setting, retrieving',
        breed_group: 'Sporting',
        life_span: '12 years',
        temperament: 'Strong Willed, Mischievous, Affectionate, Energetic, Playful, Companionable, Gentle, Hard-working, Intelligent, Eager, People-Oriented',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/EnglishSetter9_fx_wb.jpg/440px-EnglishSetter9_fx_wb.jpg"
      },
      { weight: { imperial: '44 - 66', metric: '20 - 30' },
        height: { imperial: '18 - 23', metric: '46 - 58' },
        name: 'English Shepherd',
        bred_for: 'Herding & guarding livestock, farm watch dog',
        breed_group: 'Working',
        life_span: '10 - 13 years',
        temperament: 'Kind, Energetic, Independent, Adaptable, Intelligent, Bossy',
        image_url: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c6/Englishshepherdsanfrancisco.jpeg/340px-Englishshepherdsanfrancisco.jpeg"
      },
      { weight: { imperial: '35 - 50', metric: '16 - 23' },
        height: { imperial: '19 - 20', metric: '48 - 51' },
        name: 'English Springer Spaniel',
        bred_for: 'Bird flushing, retrieving',
        breed_group: 'Sporting',
        life_span: '12 - 14 years',
        temperament: 'Affectionate, Cheerful, Alert, Intelligent, Attentive, Active',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/7/71/EnglishSpringerSpan2_wb.jpg"
      },
      { weight: { imperial: '8 - 14', metric: '4 - 6' },
        height: { imperial: '10', metric: '25' },
        name: 'English Toy Spaniel',
        bred_for: 'Companion of kings',
        breed_group: 'Toy',
        life_span: '10 - 12 years',
        temperament: 'Affectionate, Reserved, Playful, Gentle, Happy, Loving',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/King_Charles_Spaniel_200.jpg/440px-King_Charles_Spaniel_200.jpg"
      },
      { weight: { imperial: '6 - 8', metric: '3 - 4' },
        height: { imperial: '10 - 12', metric: '25 - 30' },
        name: 'English Toy Terrier',
        bred_for: 'Rat-baiting',
        life_span: '12 - 13 years',
        temperament: 'Stubborn, Alert, Companionable, Intelligent, Cunning, Trainable',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/English_Toy_Terrier_600_01.jpg/440px-English_Toy_Terrier_600_01.jpg"
      },
      { weight: { imperial: '40 - 70', metric: '18 - 32' },
        height: { imperial: '20.5 - 23.5', metric: '52 - 60' },
        name: 'Eurasier',
        bred_for: 'Companionship',
        breed_group: 'Non-Sporting',
        life_span: '12 - 14 years',
        temperament: 'Alert, Reserved, Intelligent, Even Tempered, Watchful, Calm',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Eurasier_BailyWtatze.jpg/440px-Eurasier_BailyWtatze.jpg"
      },
      { weight: { imperial: '35 - 50', metric: '16 - 23' },
        height: { imperial: '17 - 18', metric: '43 - 46' },
        name: 'Field Spaniel',
        bred_for: 'Bird flushing, retrieving',
        breed_group: 'Sporting',
        life_span: '11 - 15 years',
        temperament: 'Docile, Cautious, Sociable, Sensitive, Adaptable, Familial',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Black_Field_Spaniel.jpg/440px-Black_Field_Spaniel.jpg"
      },
      { weight: { imperial: '33 - 53', metric: '15 - 24' },
        height: { imperial: '16 - 21', metric: '41 - 53' },
        name: 'Finnish Lapphund',
        bred_for: 'Herding reindeer',
        breed_group: 'Herding',
        life_span: '12 - 15 years',
        temperament: 'Friendly, Keen, Faithful, Calm, Courageous',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Finnish_Lapphund_Glenchess_Revontuli.jpg/440px-Finnish_Lapphund_Glenchess_Revontuli.jpg"
      },
      { weight: { imperial: '23 - 28', metric: '10 - 13' },
        height: { imperial: '15.5 - 20', metric: '39 - 51' },
        name: 'Finnish Spitz',
        bred_for: 'Hunting birds, small mammals',
        breed_group: 'Non-Sporting',
        life_span: '12 - 15 years',
        temperament: 'Playful, Loyal, Independent, Intelligent, Happy, Vocal',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Finnish_Spitz_600.jpg/440px-Finnish_Spitz_600.jpg"
      },
      { weight: { imperial: '28', metric: '13' },
        height: { imperial: '11 - 12', metric: '28 - 30' },
        name: 'French Bulldog',
        bred_for: 'Lapdog',
        breed_group: 'Non-Sporting',
        life_span: '9 - 11 years',
        temperament: 'Playful, Affectionate, Keen, Sociable, Lively, Alert, Easygoing, Patient, Athletic, Bright',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Supermillion_Visuals_-_Aston_Fresh_Park_1-02601.jpg/440px-Supermillion_Visuals_-_Aston_Fresh_Park_1-02601.jpg"
      },
      { weight: { imperial: '25 - 45', metric: '11 - 20' },
        height: { imperial: '17 - 20', metric: '43 - 51' },
        name: 'German Pinscher',
        bred_for: 'Watchdog, Hunting vermin on the farm.',
        breed_group: 'Working',
        life_span: '12 - 14 years',
        temperament: 'Spirited, Lively, Intelligent, Loving, Even Tempered, Familial',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/GermanPinscher_RestingOnAChair.jpg/440px-GermanPinscher_RestingOnAChair.jpg"
      },
      { weight: { imperial: '50 - 90', metric: '23 - 41' },
        height: { imperial: '22 - 26', metric: '56 - 66' },
        name: 'German Shepherd Dog',
        bred_for: 'Herding, Guard dog',
        breed_group: 'Herding',
        life_span: '10 - 13 years',
        temperament: 'Alert, Loyal, Obedient, Curious, Confident, Intelligent, Watchful, Courageous',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Deutscher_Schaeferhund01.2.jpg/879px-Deutscher_Schaeferhund01.2.jpg"
      },
      { weight: { imperial: '45 - 70', metric: '20 - 32' },
        height: { imperial: '21 - 25', metric: '53 - 64' },
        name: 'German Shorthaired Pointer',
        bred_for: 'General hunting',
        breed_group: 'Sporting',
        life_span: '12 - 14 years',
        temperament: 'Boisterous, Bold, Affectionate, Intelligent, Cooperative, Trainable',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Duitse_staande_korthaar_10-10-2.jpg/440px-Duitse_staande_korthaar_10-10-2.jpg"
      },
      { weight: { imperial: '65 - 90', metric: '29 - 41' },
        height: { imperial: '23.5 - 27.5', metric: '60 - 70' },
        name: 'Giant Schnauzer',
        bred_for: 'Herding, guarding',
        breed_group: 'Working',
        life_span: '10 - 12 years',
        temperament: 'Strong Willed, Kind, Loyal, Intelligent, Dominant, Powerful',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Riesenschnauzerhane.jpg/440px-Riesenschnauzerhane.jpg"
      },
      { weight: { imperial: '32 - 40', metric: '15 - 18' },
        height: { imperial: '12.5 - 14', metric: '32 - 36' },
        name: 'Glen of Imaal Terrier',
        bred_for: 'Rid the home and farm of vermin, and hunt badger and fox',
        breed_group: 'Terrier',
        life_span: '12 - 15 years',
        temperament: 'Spirited, Agile, Loyal, Gentle, Active, Courageous',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Wheaten_glen_of_imaal.jpg/440px-Wheaten_glen_of_imaal.jpg"
      },
      { weight: { imperial: '55 - 75', metric: '25 - 34' },
        height: { imperial: '21.5 - 24', metric: '55 - 61' },
        name: 'Golden Retriever',
        bred_for: 'Retrieving',
        breed_group: 'Sporting',
        life_span: '10 - 12 years',
        temperament: 'Intelligent, Kind, Reliable, Friendly, Trustworthy, Confident',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Golden_Retriever_Carlos_%2810581910556%29.jpg/440px-Golden_Retriever_Carlos_%2810581910556%29.jpg"
      },
      { weight: { imperial: '45 - 80', metric: '20 - 36' },
        height: { imperial: '23 - 27', metric: '58 - 69' },
        name: 'Gordon Setter',
        bred_for: 'Find and point gamebirds',
        breed_group: 'Sporting',
        life_span: '10 - 12 years',
        temperament: 'Fearless, Alert, Loyal, Confident, Gay, Eager',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Nike_the_Gordon_Setter_%2818_June_2005%29.jpg/440px-Nike_the_Gordon_Setter_%2818_June_2005%29.jpg"
      },
      { weight: { imperial: '110 - 190', metric: '50 - 86' },
        height: { imperial: '28 - 32', metric: '71 - 81' },
        name: 'Great Dane',
        bred_for: 'Hunting & holding boars, Guardian',
        breed_group: 'Working',
        life_span: '7 - 10 years',
        temperament: 'Friendly, Devoted, Reserved, Gentle, Confident, Loving',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Gt._Dane%2C_Lucy.JPG/440px-Gt._Dane%2C_Lucy.JPG"
      },
      { weight: { imperial: '85 - 115', metric: '39 - 52' },
        height: { imperial: '25 - 32', metric: '64 - 81' },
        name: 'Great Pyrenees',
        bred_for: 'Sheep guardian',
        breed_group: 'Working',
        life_span: '10 - 12 years',
        temperament: 'Strong Willed, Fearless, Affectionate, Patient, Gentle, Confident',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Great_Pyrenees_Mountain_Dog.jpg/440px-Great_Pyrenees_Mountain_Dog.jpg"
      },
      { weight: { imperial: '50 - 70', metric: '23 - 32' },
        height: { imperial: '27 - 30', metric: '69 - 76' },
        name: 'Greyhound',
        bred_for: 'Coursing hares',
        breed_group: 'Hound',
        life_span: '10 - 13 years',
        temperament: 'Affectionate, Athletic, Gentle, Intelligent, Quiet, Even Tempered',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/GraceTheGreyhound.jpg/440px-GraceTheGreyhound.jpg"
      },
      { weight: { imperial: '12', metric: '5' },
        height: { imperial: '9 - 11', metric: '23 - 28' },
        name: 'Griffon Bruxellois',
        bred_for: 'Hunt and kill vermin in stables',
        life_span: '10 – 15 years',
        temperament: 'Self-important, Inquisitive, Alert, Companionable, Sensitive, Watchful',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/2/23/Monkey_Bizniz_Drama_Queen.jpg"
      },
      { weight: { imperial: '40 - 60', metric: '18 - 27' },
        height: { imperial: '18 - 22', metric: '46 - 56' },
        name: 'Harrier',
        bred_for: 'Hunting hares by trailing them',
        breed_group: 'Hound',
        life_span: '12 - 15 years',
        temperament: 'Outgoing, Friendly, Cheerful, Sweet-Tempered, Tolerant, Active',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Harrier_tricolour.jpg/440px-Harrier_tricolour.jpg"
      },
      { weight: { imperial: '7 - 13', metric: '3 - 6' },
        height: { imperial: '8.5 - 11.5', metric: '22 - 29' },
        name: 'Havanese',
        bred_for: 'Companionship',
        breed_group: 'Toy',
        life_span: '14 - 15 years',
        temperament: 'Affectionate, Responsive, Playful, Companionable, Gentle, Intelligent',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/A_Havanese_judging.jpg/440px-A_Havanese_judging.jpg"
      },
      { weight: { imperial: '35 - 70', metric: '16 - 32' },
        height: { imperial: '24 - 27', metric: '61 - 69' },
        name: 'Irish Setter',
        bred_for: 'Bird setting, retrieving',
        breed_group: 'Sporting',
        life_span: '10 - 11 years',
        temperament: 'Affectionate, Energetic, Lively, Independent, Playful, Companionable',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Can_Setter_dog_GFDL.jpg/440px-Can_Setter_dog_GFDL.jpg"
      },
      { weight: { imperial: '25 - 27', metric: '11 - 12' },
        height: { imperial: '18', metric: '46' },
        name: 'Irish Terrier',
        breed_group: 'Terrier',
        life_span: '12 - 16 years',
        temperament: 'Respectful, Lively, Intelligent, Dominant, Protective, Trainable',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/IrishTerrierSydenhamHillWoods.jpg/440px-IrishTerrierSydenhamHillWoods.jpg"
      },
      { weight: { imperial: '105 - 180', metric: '48 - 82' },
        height: { imperial: '30 - 35', metric: '76 - 89' },
        name: 'Irish Wolfhound',
        bred_for: 'Coursing wolves, elk',
        breed_group: 'Hound',
        life_span: '6 - 8 years',
        temperament: 'Sweet-Tempered, Loyal, Dignified, Patient, Thoughtful, Generous',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/%282%29_Irish_Wolfhound_4.jpg/440px-%282%29_Irish_Wolfhound_4.jpg"
      },
      { weight: { imperial: '7 - 15', metric: '3 - 7' },
        height: { imperial: '13 - 15', metric: '33 - 38' },
        name: 'Italian Greyhound',
        bred_for: 'Lapdog',
        breed_group: 'Toy',
        life_span: '12 - 15 years',
        temperament: 'Mischievous, Affectionate, Agile, Athletic, Companionable, Intelligent',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/ItalianGreyhound.jpg/440px-ItalianGreyhound.jpg"
      },
        { weight: { imperial: '4 - 9', metric: '2 - 4' },
        height: { imperial: '8 - 11', metric: '20 - 28' },
        name: 'Japanese Chin',
        bred_for: 'Lapdog',
        breed_group: 'Toy',
        life_span: '12 - 14 years',
        temperament: 'Alert, Loyal, Independent, Intelligent, Loving, Cat-like',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/AttentiveChin.JPG/440px-AttentiveChin.JPG"
      },
      { weight: { imperial: '15 - 19', metric: '7 - 9' },
        height: { imperial: '12 - 15', metric: '30 - 38' },
        name: 'Japanese Spitz',
        bred_for: 'Companion',
        life_span: '10 – 16 years',
        temperament: 'Affectionate, Obedient, Playful, Companionable, Intelligent, Proud',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Japspitzpup.jpg/440px-Japspitzpup.jpg"
      },
      { weight: { imperial: '35 - 45', metric: '16 - 20' },
        height: { imperial: '17 - 18', metric: '43 - 46' },
        name: 'Keeshond',
        bred_for: 'Barge watchdog',
        breed_group: 'Non-Sporting',
        life_span: '12 - 15 years',
        temperament: 'Agile, Obedient, Playful, Quick, Sturdy, Bright',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Keeshond_Majic_standing_cropped.jpg/440px-Keeshond_Majic_standing_cropped.jpg"
      },
      { weight: { imperial: '80 - 100', metric: '36 - 45' },
        height: { imperial: '25.5 - 27.5', metric: '65 - 70' },
        name: 'Komondor',
        bred_for: 'Sheep guardian',
        breed_group: 'Working',
        life_span: '10 - 12 years',
        temperament: 'Steady, Fearless, Affectionate, Independent, Gentle, Calm',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Komondor_delvin.jpg/440px-Komondor_delvin.jpg"
      },
      { weight: { imperial: '20 - 30', metric: '9 - 14' },
        height: { imperial: '14 - 16', metric: '36 - 41' },
        name: 'Kooikerhondje',
        bred_for: 'Luring ducks into traps - "tolling"',
        breed_group: 'Sporting',
        life_span: '12 - 15 years',
        temperament: 'Benevolent, Agile, Alert, Intelligent, Active, Territorial',
        image_url: ""
      },
      { weight: { imperial: '70 - 115', metric: '32 - 52' },
        height: { imperial: '26 - 30', metric: '66 - 76' },
        name: 'Kuvasz',
        bred_for: 'Guardian, hunting large game',
        breed_group: 'Working',
        life_span: '8 - 10 years',
        temperament: 'Clownish, Loyal, Patient, Independent, Intelligent, Protective',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Kooiker03.jpg/440px-Kooiker03.jpg"
      },
      { weight: { imperial: '55 - 80', metric: '25 - 36' },
        height: { imperial: '21.5 - 24.5', metric: '55 - 62' },
        name: 'Labrador Retriever',
        bred_for: 'Water retrieving',
        breed_group: 'Sporting',
        life_span: '10 - 13 years',
        temperament: 'Kind, Outgoing, Agile, Gentle, Intelligent, Trusting, Even Tempered',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Labrador_on_Quantock_%282175262184%29.jpg/440px-Labrador_on_Quantock_%282175262184%29.jpg"
      },
      { weight: { imperial: '24 - 35', metric: '11 - 16' },
        height: { imperial: '16 - 19', metric: '41 - 48' },
        name: 'Lagotto Romagnolo',
        bred_for: 'Water retrieval dog in the marshes of Romagna',
        breed_group: 'Sporting',
        life_span: '14 - 16 years',
        temperament: 'Keen, Loyal, Companionable, Loving, Active, Trainable',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Lagotto_Romagnolo.jpg/440px-Lagotto_Romagnolo.jpg"
      },
      { weight: { imperial: '6 - 13', metric: '3 - 6' },
        height: { imperial: '10 - 12', metric: '25 - 30' },
        name: 'Lancashire Heeler',
        bred_for: 'Cattle herding, Ratting, Driving cattle to market.',
        life_span: '12 – 15 years',
        temperament: 'Clever, Friendly, Alert, Intelligent',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Lancashire_Heeler_600.jpg/440px-Lancashire_Heeler_600.jpg"
      },
      { weight: { imperial: '120 - 170', metric: '54 - 77' },
        height: { imperial: '25.5 - 31.5', metric: '65 - 80' },
        name: 'Leonberger',
        bred_for: 'Guardian, appearance.',
        breed_group: 'Working',
        life_span: '6 - 8 years',
        temperament: 'Obedient, Fearless, Loyal, Companionable, Adaptable, Loving',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Leonberg-Male-Adulte-Ursus.jpg/440px-Leonberg-Male-Adulte-Ursus.jpg"
      },
      { weight: { imperial: '12 - 18', metric: '5 - 8' },
        height: { imperial: '10 - 11', metric: '25 - 28' },
        name: 'Lhasa Apso',
        bred_for: 'Guarding inside the home, companion',
        breed_group: 'Non-Sporting',
        life_span: '12 - 15 years',
        temperament: 'Steady, Fearless, Friendly, Devoted, Assertive, Spirited, Energetic, Lively, Alert, Obedient, Playful, Intelligent',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Aishia.jpg/440px-Aishia.jpg"
      },
      { weight: { imperial: '4 - 7', metric: '2 - 3' },
        height: { imperial: '8 - 10', metric: '20 - 25' },
        name: 'Maltese',
        bred_for: 'Lapdog',
        breed_group: 'Toy',
        life_span: '15 - 18 years',
        temperament: 'Playful, Docile, Fearless, Affectionate, Sweet-Tempered, Lively, Responsive, Easygoing, Gentle, Intelligent, Active',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Maltese_600.jpg/440px-Maltese_600.jpg"
      },
      { weight: { imperial: '20 - 40', metric: '9 - 18' },
        height: { imperial: '13 - 18', metric: '33 - 46' },
        name: 'Miniature American Shepherd',
        breed_group: 'Herding',
        life_span: '12 - 15 years',
        temperament: 'Energetic, Loyal, Intelligent, Trainable',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Blue_Merle_Miniature_American_Shepherd_in_Grass.jpg/440px-Blue_Merle_Miniature_American_Shepherd_in_Grass.jpg"
      },
      { weight: { imperial: '8 - 11', metric: '4 - 5' },
        height: { imperial: '10 - 12.5', metric: '25 - 32' },
        name: 'Miniature Pinscher',
        bred_for: 'Small vermin hunting',
        breed_group: 'Toy',
        life_span: '15 years',
        temperament: 'Clever, Outgoing, Friendly, Energetic, Responsive, Playful',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Miniature_pinscher.jpg/440px-Miniature_pinscher.jpg"
      },
      { weight: { imperial: '11 - 20', metric: '5 - 9' },
        height: { imperial: '12 - 14', metric: '30 - 36' },
        name: 'Miniature Schnauzer',
        bred_for: 'Ratting',
        breed_group: 'Terrier',
        life_span: '12 - 14 years',
        temperament: 'Fearless, Friendly, Spirited, Alert, Obedient, Intelligent',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Welsh_Terrier_%2811120917415%29.jpg/550px-Welsh_Terrier_%2811120917415%29.jpg"
      },
      { weight: { imperial: '100 - 150', metric: '45 - 68' },
        height: { imperial: '26 - 28', metric: '66 - 71' },
        name: 'Newfoundland',
        bred_for: 'All purpose water dog, fishing aid',
        breed_group: 'Working',
        life_span: '8 - 10 years',
        temperament: 'Sweet-Tempered, Gentle, Trainable',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Newfoundland_dog_Smoky.jpg/440px-Newfoundland_dog_Smoky.jpg"
      },
      { weight: { imperial: '11 - 12', metric: '5 - 5' },
        height: { imperial: '9 - 10', metric: '23 - 25' },
        name: 'Norfolk Terrier',
        bred_for: 'Ratting, fox bolting',
        breed_group: 'Terrier',
        life_span: '12 - 15 years',
        temperament: 'Self-confidence, Fearless, Spirited, Companionable, Happy, Lovable',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Norfolk_terrier_CAC.jpg/440px-Norfolk_terrier_CAC.jpg"
      },
      { weight: { imperial: '11 - 12', metric: '5 - 5' },
        height: { imperial: '10', metric: '25' },
        name: 'Norwich Terrier',
        bred_for: 'Ratting, fox bolting',
        breed_group: 'Terrier',
        life_span: '12 - 15 years',
        temperament: 'Hardy, Affectionate, Energetic, Sensitive, Intelligent',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Norwich_Terrier2.jpg/440px-Norwich_Terrier2.jpg"
      },
      { weight: { imperial: '35 - 50', metric: '16 - 23' },
        height: { imperial: '17 - 21', metric: '43 - 53' },
        name: 'Nova Scotia Duck Tolling Retriever',
        breed_group: 'Sporting',
        life_span: '12 - 14 years',
        temperament: 'Outgoing, Alert, Patient, Intelligent, Loving',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Duck_Toller.jpg/440px-Duck_Toller.jpg"
      },
      { weight: { imperial: '60 - 100', metric: '27 - 45' },
        height: { imperial: '21', metric: '53' },
        name: 'Old English Sheepdog',
        bred_for: 'Driving sheep, cattle',
        breed_group: 'Herding',
        life_span: '10 - 12 years',
        temperament: 'Sociable, Bubbly, Playful, Adaptable, Intelligent, Loving',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Old_English_Sheep_Dog.JPG/440px-Old_English_Sheep_Dog.JPG"
      },
      { weight: { imperial: '65 – 85', metric: 'NaN' },
        height: { imperial: '15 - 19', metric: '38 - 48' },
        name: 'Olde English Bulldogge',
        life_span: '9 – 14 years',
        temperament: 'Friendly, Alert, Confident, Loving, Courageous, Strong',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/UKC_Olde_English_Bulldogge_Male.jpg/440px-UKC_Olde_English_Bulldogge_Male.jpg"
      },
      { weight: { imperial: '3 - 12', metric: '1 - 5' },
        height: { imperial: '8 - 11', metric: '20 - 28' },
        name: 'Papillon',
        bred_for: 'Lapdog',
        breed_group: 'Toy',
        life_span: '13 - 17 years',
        temperament: 'Hardy, Friendly, Energetic, Alert, Intelligent, Happy',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Papillon_sitting_Flickr.jpg/435px-Papillon_sitting_Flickr.jpg"
      },
      { weight: { imperial: '14', metric: '6' },
        height: { imperial: '6 - 9', metric: '15 - 23' },
        name: 'Pekingese',
        bred_for: 'Lapdog',
        breed_group: 'Toy',
        life_span: '14 - 18 years',
        temperament: 'Opinionated, Good-natured, Stubborn, Affectionate, Aggressive, Intelligent',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Pekingese_Image_002.jpg/440px-Pekingese_Image_002.jpg"
      },
      { weight: { imperial: '25 - 30', metric: '11 - 14' },
        height: { imperial: '10 - 12', metric: '25 - 30' },
        name: 'Pembroke Welsh Corgi',
        bred_for: 'Driving stock to market in northern Wales',
        breed_group: 'Herding',
        life_span: '12 - 14 years',
        temperament: 'Tenacious, Outgoing, Friendly, Bold, Playful, Protective',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Welchcorgipembroke.JPG/440px-Welchcorgipembroke.JPG"
      },
      { weight: { imperial: '88 - 110', metric: '40 - 50' },
        height: { imperial: '22 - 25.5', metric: '56 - 65' },
        name: 'Perro de Presa Canario',
        breed_group: 'Working',
        life_span: '10 - 12 years',
        temperament: 'Strong Willed, Suspicious, Gentle, Dominant, Calm',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Dogo_Canario.jpg"
      },
      { weight: { imperial: '40 - 60', metric: '18 - 27' },
        height: { imperial: '21 - 25', metric: '53 - 64' },
        name: 'Pharaoh Hound',
        bred_for: 'Hunting rabbits',
        breed_group: 'Hound',
        life_span: '12 - 14 years',
        temperament: 'Affectionate, Sociable, Playful, Intelligent, Active, Trainable',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Pies_faraona_e34.jpg/440px-Pies_faraona_e34.jpg"
      },
      { weight: { imperial: '40 - 60', metric: '18 - 27' },
        height: { imperial: '20 - 25', metric: '51 - 64' },
        name: 'Plott',
        bred_for: 'Hunting big-game like Boar.',
        breed_group: 'Hound',
        life_span: '12 - 14 years',
        temperament: 'Bold, Alert, Loyal, Intelligent',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Plotthund_Kynnagardens_Ziggy_Lundamo.JPG/440px-Plotthund_Kynnagardens_Ziggy_Lundamo.JPG"
      },
      { weight: { imperial: '3 - 7', metric: '1 - 3' },
        height: { imperial: '8 - 12', metric: '20 - 30' },
        name: 'Pomeranian',
        bred_for: 'Companion',
        breed_group: 'Toy',
        life_span: '15 years',
        temperament: 'Extroverted, Friendly, Sociable, Playful, Intelligent, Active',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Pomeranian.JPG/440px-Pomeranian.JPG"
      },
      { weight: { imperial: '14 - 18', metric: '6 - 8' },
        height: { imperial: '10 - 12', metric: '25 - 30' },
        name: 'Pug',
        bred_for: 'Lapdog',
        breed_group: 'Toy',
        life_span: '12 - 14 years',
        temperament: 'Docile, Clever, Charming, Stubborn, Sociable, Playful, Quiet, Attentive',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Mops_oct09_cropped2.jpg/440px-Mops_oct09_cropped2.jpg"
      },
      { weight: { imperial: '25 - 35', metric: '11 - 16' },
        height: { imperial: '16 - 17', metric: '41 - 43' },
        name: 'Puli',
        bred_for: 'Herding',
        breed_group: 'Herding',
        life_span: '12 - 16 Years years',
        temperament: 'Energetic, Agile, Loyal, Obedient, Intelligent, Faithful',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/PuliBlack_wb.jpg/440px-PuliBlack_wb.jpg"
      },
      { weight: { imperial: '18 - 33', metric: '8 - 15' },
        height: { imperial: '15 - 18.5', metric: '38 - 47' },
        name: 'Pumi',
        breed_group: 'Herding',
        life_span: '13 - 15 years',
        temperament: 'Lively, Reserved, Intelligent, Active, Protective, Vocal',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Pumi_2.jpg/440px-Pumi_2.jpg"
      },
      { weight: { imperial: '8 - 25', metric: '4 - 11' },
        height: { imperial: '10 - 13', metric: '25 - 33' },
        name: 'Rat Terrier',
        breed_group: 'Terrier',
        life_span: '12 - 18 years',
        temperament: 'Affectionate, Lively, Inquisitive, Alert, Intelligent, Loving',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/AmRatTerr2_wb.jpg/440px-AmRatTerr2_wb.jpg"
      },
      { weight: { imperial: '45 - 80', metric: '20 - 36' },
        height: { imperial: '21 - 27', metric: '53 - 69' },
        name: 'Redbone Coonhound',
        bred_for: 'Hunting raccoon, deer, bear, and cougar.',
        breed_group: 'Hound',
        life_span: '10 - 12 years',
        temperament: 'Affectionate, Energetic, Independent, Companionable, Familial, Unflappable',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Redbone-coonhound-detail.jpg/440px-Redbone-coonhound-detail.jpg"
      },
      { weight: { imperial: '75 - 80', metric: '34 - 36' },
        height: { imperial: '24 - 27', metric: '61 - 69' },
        name: 'Rhodesian Ridgeback',
        bred_for: 'Big game hunting, guarding',
        breed_group: 'Hound',
        life_span: '10 - 12 years',
        temperament: 'Strong Willed, Mischievous, Loyal, Dignified, Sensitive, Intelligent',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Rhodesian_ridgeback.jpg/440px-Rhodesian_ridgeback.jpg"
      },
      { weight: { imperial: '75 - 110', metric: '34 - 50' },
        height: { imperial: '22 - 27', metric: '56 - 69' },
        name: 'Rottweiler',
        bred_for: 'Cattle drover, guardian, draft',
        breed_group: 'Working',
        life_span: '8 - 10 years',
        temperament: 'Steady, Good-natured, Fearless, Devoted, Alert, Obedient, Confident, Self-assured, Calm, Courageous',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Rottweiler_standing_facing_left.jpg/440px-Rottweiler_standing_facing_left.jpg"
      },
      { weight: { imperial: '3 - 6', metric: '1 - 3' },
        height: { imperial: '7.5 - 10.5', metric: '19 - 27' },
        name: 'Russian Toy',
        breed_group: 'Toy',
        life_span: '10 - 12 years',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/RusskiyToyWelpe9Mon.JPG/440px-RusskiyToyWelpe9Mon.JPG"
      },
      { weight: { imperial: '130 - 180', metric: '59 - 82' },
        height: { imperial: '25.5 - 27.5', metric: '65 - 70' },
        name: 'Saint Bernard',
        bred_for: 'Draft, search, rescue',
        breed_group: 'Working',
        life_span: '7 - 10 years',
        temperament: 'Friendly, Lively, Gentle, Watchful, Calm',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Hummel_Vedor_vd_Robandahoeve.jpg/440px-Hummel_Vedor_vd_Robandahoeve.jpg"
      },
      { weight: { imperial: '35 - 65', metric: '16 - 29' },
        height: { imperial: '23 - 28', metric: '58 - 71' },
        name: 'Saluki',
        bred_for: 'Coursing gazelle and hare',
        breed_group: 'Hound',
        life_span: '12 - 14 years',
        temperament: 'Aloof, Reserved, Intelligent, Quiet',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Saluki_in_India.jpg/440px-Saluki_in_India.jpg"
      },
      { weight: { imperial: '50 - 60', metric: '23 - 27' },
        height: { imperial: '19 - 23.5', metric: '48 - 60' },
        name: 'Samoyed',
        bred_for: 'Herding reindeer, guardian, draft',
        breed_group: 'Working',
        life_span: '12 - 14 years',
        temperament: 'Stubborn, Friendly, Sociable, Lively, Alert, Playful',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Samoyed-sweetjedysamoyeds.jpg/440px-Samoyed-sweetjedysamoyeds.jpg"
      },
      { weight: { imperial: '10 - 16', metric: '5 - 7' },
        height: { imperial: '10 - 13', metric: '25 - 33' },
        name: 'Schipperke',
        bred_for: 'Barge watchdog',
        breed_group: 'Non-Sporting',
        life_span: '13 - 15 years',
        temperament: 'Fearless, Agile, Curious, Independent, Confident, Faithful',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Schipperke0001.jpg/440px-Schipperke0001.jpg"
      },
      { weight: { imperial: '70 - 130', metric: '32 - 59' },
        height: { imperial: '28 - 32', metric: '71 - 81' },
        name: 'Scottish Deerhound',
        bred_for: 'Coursing deer',
        breed_group: 'Hound',
        life_span: '8 - 10 years',
        temperament: 'Docile, Friendly, Dignified, Gentle',
        image_url: "https://upload.wikimedia.org/wikipedia/en/5/5b/Deerhound_Fernhill%27s_Kendra.jpg"
      },
      { weight: { imperial: '18 - 22', metric: '8 - 10' },
        height: { imperial: '10', metric: '25' },
        name: 'Scottish Terrier',
        bred_for: 'Vermin hunting',
        breed_group: 'Terrier',
        life_span: '11 - 13 years',
        temperament: 'Feisty, Alert, Independent, Playful, Quick, Self-assured',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Scottish_Terrier_Photo_of_Face.jpg/440px-Scottish_Terrier_Photo_of_Face.jpg"
      },
      { weight: { imperial: '30', metric: '14' },
        height: { imperial: '13 - 16', metric: '33 - 41' },
        name: 'Shetland Sheepdog',
        bred_for: 'Sheep herding',
        breed_group: 'Herding',
        life_span: '12 - 14 years',
        temperament: 'Affectionate, Lively, Responsive, Alert, Loyal, Reserved, Playful, Gentle, Intelligent, Active, Trainable, Strong',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Shetland_Sheepdog_600.jpg/440px-Shetland_Sheepdog_600.jpg"
      },
      { weight: { imperial: '17 - 23', metric: '8 - 10' },
        height: { imperial: '13.5 - 16.5', metric: '34 - 42' },
        name: 'Shiba Inu',
        bred_for: 'Hunting in the mountains of Japan, Alert Watchdog',
        breed_group: 'Non-Sporting',
        life_span: '12 - 16 years',
        temperament: 'Charming, Fearless, Keen, Alert, Confident, Faithful',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Taka_Shiba.jpg/440px-Taka_Shiba.jpg"
      },
      { weight: { imperial: '9 - 16', metric: '4 - 7' },
        height: { imperial: '8 - 11', metric: '20 - 28' },
        name: 'Shih Tzu',
        bred_for: 'Lapdog',
        breed_group: 'Toy',
        life_span: '10 - 18 years',
        temperament: 'Clever, Spunky, Outgoing, Friendly, Affectionate, Lively, Alert, Loyal, Independent, Playful, Gentle, Intelligent, Happy, Active, Courageous',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/d/df/Shihtzu_%28cropped%29.jpg"
      },
      { weight: { imperial: '120 - 140', metric: '54 - 64' },
        height: { imperial: '26 - 30', metric: '66 - 76' },
        name: 'Shiloh Shepherd',
        bred_for: 'Swimming, Carrying backpacks, Pulling carts or sleds',
        life_span: '9 – 14 years',
        temperament: 'Outgoing, Loyal, Companionable, Gentle, Loving, Trainable',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/d/d2/Plushcoatshilohshepherd.jpg"
      },
      { weight: { imperial: '35 - 60', metric: '16 - 27' },
        height: { imperial: '20 - 23.5', metric: '51 - 60' },
        name: 'Siberian Husky',
        bred_for: 'Sled pulling',
        breed_group: 'Working',
        life_span: '12 years',
        temperament: 'Outgoing, Friendly, Alert, Gentle, Intelligent',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Black-Magic-Big-Boy.jpg/440px-Black-Magic-Big-Boy.jpg"
      },
      { weight: { imperial: '8 - 10', metric: '4 - 5' },
        height: { imperial: '9 - 10', metric: '23 - 25' },
        name: 'Silky Terrier',
        bred_for: 'Small vermin hunting, companionship',
        breed_group: 'Toy',
        life_span: '12 - 15 years',
        temperament: 'Friendly, Responsive, Inquisitive, Alert, Quick, Joyful',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Australian_Silky_Terrier_Alana_Of_Silky%27s_Dream.jpg/440px-Australian_Silky_Terrier_Alana_Of_Silky%27s_Dream.jpg"
      },
      { weight: { imperial: 'up - 18', metric: 'NaN - 8' },
        height: { imperial: '15.5', metric: '39' },
        name: 'Smooth Fox Terrier',
        bred_for: 'Fox bolting',
        breed_group: 'Terrier',
        life_span: '12 - 14 years',
        temperament: 'Fearless, Affectionate, Alert, Playful, Intelligent, Active',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/4/47/Patrick_the_Smooth_Fox_Terrier.jpg"
      },
      { weight: { imperial: '30 - 40', metric: '14 - 18' },
        height: { imperial: '16 - 18', metric: '41 - 46' },
        name: 'Soft Coated Wheaten Terrier',
        bred_for: 'Vermin hunting, guarding, all-around farm helper',
        breed_group: 'Terrier',
        life_span: '12 - 15 years',
        temperament: 'Affectionate, Spirited, Energetic, Playful, Intelligent, Faithful',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Australian_Grand_Champion_Dancestar_Zero_O_Seven_%22Bondy%22.jpg/440px-Australian_Grand_Champion_Dancestar_Zero_O_Seven_%22Bondy%22.jpg"
      },
      { weight: { imperial: '30 - 50', metric: '14 - 23' },
        height: { imperial: '16 - 20', metric: '41 - 51' },
        name: 'Spanish Water Dog',
        bred_for: 'Herding flocks of sheep and goats from one pasture to another',
        breed_group: 'Sporting',
        life_span: '12 - 15 years',
        temperament: 'Trainable, Diligent, Affectionate, Loyal, Athletic, Intelligent',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Perro_agua.jpg/440px-Perro_agua.jpg"
      },
      { weight: { imperial: '61 - 85', metric: '28 - 39' },
        height: { imperial: '22.5 - 27.5', metric: '57 - 70' },
        name: 'Spinone Italiano',
        breed_group: 'Sporting',
        life_span: '10 - 12 years',
        temperament: 'Docile, Friendly, Affectionate, Loyal, Patient, Gentle',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/05042363_Spinone_braun.jpg/440px-05042363_Spinone_braun.jpg"
      },
      { weight: { imperial: '24 - 38', metric: '11 - 17' },
        height: { imperial: '14 - 16', metric: '36 - 41' },
        name: 'Staffordshire Bull Terrier',
        bred_for: '',
        breed_group: 'Terrier',
        life_span: '12 - 14 years',
        temperament: 'Reliable, Fearless, Bold, Affectionate, Loyal, Intelligent, Courageous',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Staffordshire-bull-terrier-white-2748733.jpg/440px-Staffordshire-bull-terrier-white-2748733.jpg"
      },
      { weight: { imperial: '30 - 50', metric: '14 - 23' },
        height: { imperial: '17.5 - 19.5', metric: '44 - 50' },
        name: 'Standard Schnauzer',
        bred_for: 'Ratting, guarding',
        breed_group: 'Working',
        life_span: '13 - 15 years',
        temperament: 'Trainable, Good-natured, Devoted, Lively, Playful, Intelligent',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/a/a1/Emppumenossa.jpg"
      },
      { weight: { imperial: '20 - 30', metric: '9 - 14' },
        height: { imperial: '11.5 - 13.5', metric: '29 - 34' },
        name: 'Swedish Vallhund',
        breed_group: 'Herding',
        life_span: '12 - 14 years',
        temperament: 'Fearless, Friendly, Energetic, Alert, Intelligent, Watchful',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/V%C3%A4stg%C3%B6taspets_hane_5_%C3%A5r.jpg/440px-V%C3%A4stg%C3%B6taspets_hane_5_%C3%A5r.jpg"
      },
      { weight: { imperial: '35 - 55', metric: '16 - 25' },
        height: { imperial: '20 - 24', metric: '51 - 61' },
        name: 'Thai Ridgeback',
        breed_group: 'Hound',
        life_span: '10 - 12 years',
        temperament: 'Protective, Loyal, Independent, Intelligent, Loving, Familial',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Thai-Ridgeback.jpg/440px-Thai-Ridgeback.jpg"
      },
      { weight: { imperial: '85 - 140', metric: '39 - 64' },
        height: { imperial: '24 - 26', metric: '61 - 66' },
        name: 'Tibetan Mastiff',
        breed_group: 'Working',
        life_span: '10 - 14 years',
        temperament: 'Strong Willed, Tenacious, Aloof, Stubborn, Intelligent, Protective',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Mastif_tybeta%C5%84ski_2009_pl3.jpg/440px-Mastif_tybeta%C5%84ski_2009_pl3.jpg"
      },
      { weight: { imperial: '9 - 15', metric: '4 - 7' },
        height: { imperial: '10', metric: '25' },
        name: 'Tibetan Spaniel',
        breed_group: 'Non-Sporting',
        life_span: '12 - 15 years',
        temperament: 'Willful, Aloof, Assertive, Independent, Playful, Intelligent, Happy',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Tibetansk_spaniel.jpg/440px-Tibetansk_spaniel.jpg"
      },
      { weight: { imperial: '20 - 24', metric: '9 - 11' },
        height: { imperial: '14 - 17', metric: '36 - 43' },
        name: 'Tibetan Terrier',
        bred_for: 'Good luck charms, mascots, watchdogs, herding dogs, and companions',
        breed_group: 'Non-Sporting',
        life_span: '12 - 15 years',
        temperament: 'Affectionate, Energetic, Amiable, Reserved, Gentle, Sensitive',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Tibet_Terrier_Bennie_%28cropped%29.jpg/440px-Tibet_Terrier_Bennie_%28cropped%29.jpg"
      },
      { weight: { imperial: '4 - 9', metric: '2 - 4' },
        height: { imperial: '8 - 11', metric: '20 - 28' },
        name: 'Toy Fox Terrier',
        breed_group: 'Toy',
        life_span: '12 - 15 years',
        temperament: 'Friendly, Spirited, Alert, Loyal, Playful, Intelligent',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Toy_Fox_Terrier_2.jpg/440px-Toy_Fox_Terrier_2.jpg"
      },
      { weight: { imperial: '45 - 80', metric: '20 - 36' },
        height: { imperial: '20 - 27', metric: '51 - 69' },
        name: 'Treeing Walker Coonhound',
        breed_group: 'Hound',
        life_span: '10 - 13 years',
        temperament: 'Clever, Affectionate, Confident, Intelligent, Loving, Trainable',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Treeing-walker-coonhound-standing.jpg/440px-Treeing-walker-coonhound-standing.jpg"
      },
      { weight: { imperial: '55 - 90', metric: '25 - 41' },
        height: { imperial: '23 - 27', metric: '58 - 69' },
        name: 'Weimaraner',
        bred_for: 'Large game trailing and versatile gundog',
        breed_group: 'Sporting',
        life_span: '12 - 15 years',
        temperament: 'Steady, Aloof, Stubborn, Energetic, Alert, Intelligent, Powerful, Fast',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Weimaraner_wb.jpg/440px-Weimaraner_wb.jpg"
      },
      { weight: { imperial: '35 - 55', metric: '16 - 25' },
        height: { imperial: '17 - 19', metric: '43 - 48' },
        name: 'Welsh Springer Spaniel',
        bred_for: 'Flushing and retrieving birds',
        breed_group: 'Sporting',
        life_span: '12 - 15 years',
        temperament: 'Stubborn, Friendly, Affectionate, Loyal, Playful, Active',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Welsh_Springer_Spaniel_1.jpg/440px-Welsh_Springer_Spaniel_1.jpg"
      },
      { weight: { imperial: '15 - 22', metric: '7 - 10' },
        height: { imperial: '10 - 11', metric: '25 - 28' },
        name: 'West Highland White Terrier',
        bred_for: 'Fox, badger, vermin hunting',
        breed_group: 'Terrier',
        life_span: '15 - 20 years',
        temperament: 'Hardy, Friendly, Alert, Independent, Gay, Active, Courageous',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/West_Highland_White_Terrier_Krakow.jpg/440px-West_Highland_White_Terrier_Krakow.jpg"
      },
      { weight: { imperial: '25 - 35', metric: '11 - 16' },
        height: { imperial: '18 - 22', metric: '46 - 56' },
        name: 'Whippet',
        bred_for: 'Coursing, racing',
        breed_group: 'Hound',
        life_span: '12 - 15 years',
        temperament: 'Friendly, Affectionate, Lively, Gentle, Intelligent, Quiet',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/WhippetWhiteSaddled_wb.jpg/440px-WhippetWhiteSaddled_wb.jpg"
      },
      { weight: { imperial: '60 - 85', metric: '27 - 39' },
        height: { imperial: '22 - 25', metric: '56 - 64' },
        name: 'White Shepherd',
        life_span: '12 – 14 years',
        temperament: 'Self-confidence, Aloof, Fearless, Alert, Companionable, Eager',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/German_Shepherd_Dog_white_long-coated.jpg/440px-German_Shepherd_Dog_white_long-coated.jpg"
      },
      { weight: { imperial: '15 - 19', metric: '7 - 9' },
        height: { imperial: '13 - 16', metric: '33 - 41' },
        name: 'Wire Fox Terrier',
        bred_for: 'Vermin hunting, fox bolting',
        life_span: '13 – 14 years',
        history: ' England',
        temperament: 'Fearless, Friendly, Bold, Keen, Alert, Quick',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Wera.JPG/440px-Wera.JPG"
      },
      { weight: { imperial: '45 - 70', metric: '20 - 32' },
        height: { imperial: '20 - 24', metric: '51 - 61' },
        name: 'Wirehaired Pointing Griffon',
        bred_for: 'Gundog, "swamp-tromping", Flushing, pointing, and retrieving water fowl & game birds',
        breed_group: 'Sporting',
        life_span: '12 - 14 years',
        temperament: 'Loyal, Gentle, Vigilant, Trainable, Proud',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/GCH_Int_Ch_UCH_Zerubbabel_von_Herrenhausen_CGC_MHA.jpg/440px-GCH_Int_Ch_UCH_Zerubbabel_von_Herrenhausen_CGC_MHA.jpg"
      },
      { weight: { imperial: '45 - 65', metric: '20 - 29' },
        height: { imperial: '21.5 - 25', metric: '55 - 64' },
        name: 'Wirehaired Vizsla',
        breed_group: 'Sporting',
        life_span: '12 - 14 years',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Dr%C3%B3tosvizsla_vadat_%C3%A1ll.jpg/440px-Dr%C3%B3tosvizsla_vadat_%C3%A1ll.jpg"
      },
      { weight: { imperial: '9 - 31', metric: '4 - 14' },
        height: { imperial: '10 - 23', metric: '25 - 58' },
        name: 'Xoloitzcuintli',
        breed_group: 'Non-Sporting',
        life_span: '12 - 14 years',
        temperament: 'Cheerful, Alert, Companionable, Intelligent, Protective, Calm',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/BIR_Grupp_5-_MEXIKANSK_NAKENHUND%2C_Lokal_Hero%E2%80%99s_King_Og_Hart%E2%80%99s_Istas_%2823607403303%29.jpg/440px-BIR_Grupp_5-_MEXIKANSK_NAKENHUND%2C_Lokal_Hero%E2%80%99s_King_Og_Hart%E2%80%99s_Istas_%2823607403303%29.jpg"
      },
      { weight: { imperial: '4 - 7', metric: '2 - 3' },
        height: { imperial: '8 - 9', metric: '20 - 23' },
        name: 'Yorkshire Terrier',
        bred_for: 'Small vermin hunting',
        breed_group: 'Toy',
        life_span: '12 - 16 years',
        temperament: 'Bold, Independent, Confident, Intelligent, Courageous',
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Henri_the_yorki_from_alabama_.jpg/440px-Henri_the_yorki_from_alabama_.jpg"
      }
    ]
end